repos:
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run pytest
        language: system
        types: [python]
        stages: [commit]
        additional_dependencies: []
        pass_filenames: true

      - id: mypy
        name: mypy
        entry: uv run mypy
        language: system
        types: [python]
        stages: [commit]
        additional_dependencies: []
        pass_filenames: true

      - id: isort
        name: isort
        entry: uv run isort
        language: system
        types: [python]
        args: ["--profile", "black"]
        stages: [commit]
        additional_dependencies: []
        pass_filenames: true
        
      - id: black
        name: black
        entry: uv run black
        language: system
        types: [python]
        stages: [commit]
        additional_dependencies: []
        pass_filenames: true

      - id: autoflake8
        name: autoflake8
        entry: uv run autoflake8
        language: system
        types: [python]
        args: ["--in-place", "--remove-duplicate-keys"]
        stages: [commit]
        additional_dependencies: []
        pass_filenames: true

      - id: flake8
        name: flake8
        entry: uv run flake8
        language: system
        types: [python]
        stages: [commit]
        additional_dependencies: []
        pass_filenames: true

